#include <ul/fs/fs_Stdio.hpp>
#include <ul/cfg/cfg_Config.hpp>
#include <ul/util/util_Json.hpp>
#include <ul/util/util_Telemetry.hpp>
#include <cstdlib>
#include <sys/stat.h>  // v2.0.3-A3: mkdir(2) for sdmc:/switch/ at boot

// ---------------------------------------------------------------------------
// BOOT-TRACE (2026-06-19): diagnostic for NRO-relaunch black-screen hang.
//
// When sdmc:/ulaunch/debug.flag exists, every major startup step writes one
// line to sdmc:/ulaunch/umenu_boot_trace.log using fopen("ab")+fwrite+fflush
// +fclose (immediate-flush, zero buffering).  The LAST line present after a
// relaunch-black reveals the exact hang point.
//
// Gate: checked once at process start.  Zero overhead when the flag is absent
// because g_bt_enabled is set by checking access() in __appInit before any
// other logging runs.  The trace predates UL_LOG_INFO so it's useful even
// when the log writer itself is suspect.
// ---------------------------------------------------------------------------
static bool g_bt_enabled = false;

// BtWrite — core trace primitive.  Called at every instrumented checkpoint.
// Uses raw POSIX file I/O so it works even if fsdev or stdio is partially
// initialised.  We fflush+fclose after every write so the log survives a
// hang/crash immediately after the call.
static void BtWrite(const char *tag) {
    if (!g_bt_enabled) return;
    FILE *f = fopen("sdmc:/ulaunch/umenu_boot_trace.log", "ab");
    if (!f) return;
    char buf[160];
    int n = ::snprintf(buf, sizeof(buf),
        "[BOOT_TRACE tick=%lu] %s\n",
        static_cast<unsigned long>(armGetSystemTick()), tag);
    if (n > 0) {
        fwrite(buf, static_cast<size_t>(n), 1, f);
        fflush(f);
    }
    fclose(f);
}

// Convenience: BtWrite + UL_LOG_INFO (called after logging is available).
#define BT(tag) BtWrite(tag)

#include <ul/menu/ui/ui_MenuApplication.hpp>
#include <ul/util/util_Size.hpp>
#include <ul/net/net_Service.hpp>
#include <ul/menu/smi/sf/sf_PrivateService.hpp>
#include <ul/menu/qdesktop/qd_ResourceLedger.hpp>
#include <ul/menu/qdesktop/qd_PerfLogger.hpp>   // W7: frame-level CSV perf logger
#include <ul/menu/am/am_LibraryAppletUtils.hpp>
#include <ul/menu/am/am_LibnxLibappletWrap.hpp>
#include <ul/audio/audio_SystemVolume.hpp>
#include <ul/menu/qdesktop/qd_Theme.hpp>       // v2.4.0: SetActiveThemePack / LoadActiveThemePack
#include <ul/menu/qdesktop/qd_LazyLoader.hpp>   // W12-LAZYTHEME: LoadAllThemeMetadata / LoadThemeAssets
#include <ul/menu/qdesktop/qd_FolderTheme.hpp>  // v3.1.1: LoadActiveWallpaperPack (decoupled from folder-theme)
#include <ul/menu/qdesktop/qd_AppletLifecycle.hpp>  // v2.8.3: applet sleep/wake hook
#include <unistd.h>                        // v2.7.0: access(F_OK) for first-boot theme seeding
#include <cerrno>                          // v2.7.0: errno after fopen/fwrite
#include <sys/stat.h>                      // v2.9.9: stat() for size-compare upgrade detection
#include <thread>                          // W17: background EnsureQosThemesOnSd
#include <atomic>                          // W17: thread-safe completion flag

using namespace ul::util::size;

// v2.9.9 — file-size helper used by EnsureQosThemesOnSd to detect stale SD
// .ultheme bundles.  Returns -1 if the file is missing or stat fails.
static long long QosFileSize(const char *path) {
    struct stat st;
    if (stat(path, &st) != 0) return -1;
    return static_cast<long long>(st.st_size);
}

// v2.7.0 — first-boot copy of the 10 Q OS .ultheme bundles from romfs:/themes/
// to sdmc:/ulaunch/themes/. Each bundle was generated by
// scripts/generate-qos-theme-icons.py and baked into romfs.bin. They live
// as real .ultheme files on the user's SD so they show up in the Themes menu
// via the standard cfg::FindThemes() scan (no parallel in-binary registry).
//
// v2.9.9 — Upgrade detection.  Previously the seed-only-if-missing guard
// (access(dst, F_OK) == 0 → skip) meant that older shipped bundles (v2.9.4
// stubs with only 3 files inside the zip) STAYED on SD across fork updates,
// and CacheActiveTheme would extract those stale stubs every time the user
// applied a theme — leaving the cache without per-category folder PNGs or
// HotCornerQ.png and forcing fallback to Glass for every other theme.
// Fix: compare romfs source size to SD destination size; if they differ,
// back up the SD copy as `.qos-prev.<size>.ultheme` and re-seed from romfs.
// User customisation: user themes use NEW filenames (`my-theme.ultheme`,
// already on SD), so the `q-os-*.ultheme` namespace is owned by Q OS and
// safe to refresh.
// Returns true if any q-os-*.ultheme bundle was refreshed (so the caller knows
// to invalidate the active theme cache and force a re-extract from the new
// bundle on the next EnsureCacheActiveTheme step).
static bool EnsureQosThemesOnSd() {
    static const char *const kQosThemes[] = {
        "q-os-0-q-os.ultheme",
        "q-os-1-neon.ultheme",
        "q-os-2-minimal.ultheme",
        "q-os-3-retro.ultheme",
        "q-os-4-cards.ultheme",
        "q-os-5-pastel.ultheme",
        "q-os-6-dark.ultheme",
        "q-os-7-gradient.ultheme",
        "q-os-8-blueprint.ultheme",
        "q-os-9-pixel.ultheme",
    };
    mkdir("sdmc:/ulaunch", 0777);
    mkdir("sdmc:/ulaunch/themes", 0777);
    bool any_written = false;
    for (const char *name : kQosThemes) {
        char dst[256];
        char src[256];
        std::snprintf(dst, sizeof(dst), "sdmc:/ulaunch/themes/%s", name);
        std::snprintf(src, sizeof(src), "romfs:/themes/%s", name);
        const long long src_sz = QosFileSize(src);
        const long long dst_sz = QosFileSize(dst);
        if (src_sz < 0) {
            UL_LOG_WARN("EnsureQosThemesOnSd: missing romfs source %s", src);
            continue;
        }
        const bool dst_exists = (dst_sz >= 0);
        if (dst_exists && dst_sz == src_sz) {
            // Same size = treat as identical content.  Skip silently.
            continue;
        }
        if (dst_exists) {
            // SD copy is a different size from the romfs copy — either a
            // stale older Q OS-shipped bundle or a user-edited variant.
            // Back it up before overwriting so nothing is irrecoverable.
            char bak[320];
            std::snprintf(bak, sizeof(bak),
                          "sdmc:/ulaunch/themes/%s.qos-prev.%lld.bak",
                          name, dst_sz);
            // Best-effort rename; if it fails we still proceed with seed
            // (so a broken SD copy doesn't permanently wedge the user out
            // of fresh Q OS themes).
            if (std::rename(dst, bak) != 0) {
                UL_LOG_WARN("EnsureQosThemesOnSd: backup rename %s -> %s "
                            "failed errno=%d (proceeding without backup)",
                            dst, bak, errno);
            } else {
                UL_LOG_INFO("EnsureQosThemesOnSd: backed up stale %s -> %s "
                            "(was %lld B, romfs source %lld B)",
                            dst, bak, dst_sz, src_sz);
            }
        }
        FILE *in = std::fopen(src, "rb");
        if (!in) {
            UL_LOG_WARN("EnsureQosThemesOnSd: cannot open romfs %s errno=%d",
                        src, errno);
            continue;
        }
        FILE *out = std::fopen(dst, "wb");
        if (!out) {
            UL_LOG_WARN("EnsureQosThemesOnSd: cannot create %s errno=%d",
                        dst, errno);
            std::fclose(in);
            continue;
        }
        char buf[65536];
        size_t n;
        while ((n = std::fread(buf, 1, sizeof(buf), in)) > 0) {
            std::fwrite(buf, 1, n, out);
        }
        std::fclose(out);
        std::fclose(in);
        any_written = true;
        UL_LOG_INFO("EnsureQosThemesOnSd: %s %s (%lld B)",
                    dst_exists ? "refreshed" : "seeded", dst, src_sz);
    }
    if (any_written) {
        fsdevCommitDevice("sdmc");
        UL_LOG_INFO("EnsureQosThemesOnSd: SD committed");
    }
    return any_written;
}

ul::menu::ui::GlobalSettings g_GlobalSettings;

// W17-FIX2: atomic completion flag for the background theme-seed thread.
// true  = thread has finished (or was never needed — all bundles up-to-date).
// false = thread is still running.
// Checked by Settings → Themes before first theme-switch in this session.
std::atomic<bool> g_qos_themes_bg_done { false };

// W17-FIX2: background wrapper that runs EnsureQosThemesOnSd off the main thread.
// W18-DIAG: temporarily unused while the bg-thread vs main-thread SD I/O race is
// eliminated as a variable.  Kept for the v3.6 boot-speed refactor.
[[maybe_unused]] static void BackgroundEnsureQosThemesOnSd() {
    const bool refreshed = EnsureQosThemesOnSd();
    if (refreshed) {
        UL_LOG_INFO("W17-FIX2: BG theme-seed: bundles upgraded — invalidating cache");
        ul::cfg::RemoveActiveThemeCache();
    }
    g_qos_themes_bg_done.store(true, std::memory_order_release);
}

// v2.0.3-A1 first-paint telemetry checkpoints. File-scope (NOT in anonymous
// namespace) so qd_DesktopIcons.cpp can extern them and emit ms deltas at the
// first OnRender call. 0 = uninitialized; populated below in main()/__appInit/MainLoop.
u64 g_qos_boot_t_appinit_ticks = 0;
u64 g_qos_boot_t_main_ticks    = 0;
u64 g_qos_boot_t_premain_ticks = 0;

namespace {

    NsApplicationControlData g_TemporaryControlData;

    bool MenuControlEntryLoadFunction(const u64 app_id, std::string &out_name, std::string &out_author, std::string &out_version) {
        if(R_FAILED(nsextGetApplicationControlData(NsApplicationControlSource_Storage, app_id, &g_TemporaryControlData, sizeof(NsApplicationControlData), nullptr))) {
            UL_LOG_WARN("Failed to get application control data for application %016lX", app_id);
            return false;
        }

        NacpLanguageEntry *lang_entry = nullptr;
        if(R_FAILED(nacpGetLanguageEntry(&g_TemporaryControlData.nacp, &lang_entry))) {
            UL_LOG_WARN("Failed to get NACP language entry for application %016lX", app_id);
            return false;
        }

        out_name = lang_entry->name;
        out_author = lang_entry->author;
        out_version = g_TemporaryControlData.nacp.display_version;
        return true;
    }

}

extern "C" {

    AppletType __nx_applet_type = AppletType_LibraryApplet; // Explicitly declare we're a library applet (need to do so for non-hbloader homebrew)
    TimeServiceType __nx_time_service_type = TimeServiceType_Menu;
    u32 __nx_fs_num_sessions = 1;
    size_t __nx_heap_size = 296_MB;

    SetSysFirmwareVersion g_FirmwareVersion;

    void __libnx_init_time();

    void __nx_win_init();
    void __nx_win_exit();

    // W6-LEDGER: ledger handles for process-lifetime services tracked in __appInit.
    // Untracked in __appExit so the Monitor Resources view shows them as live for
    // the entire process lifetime.
    static uint64_t g_svc_lh_setsys_ = 0;
    static uint64_t g_svc_lh_account_ = 0;
    static uint64_t g_svc_lh_ns_      = 0;
    static uint64_t g_svc_lh_psm_     = 0;

    // EARLY-TRACE (v3.7.52, pre-fsdev pinpoint): a raw-FsFileSystem writer that
    // works the instant fsInitialize() returns — BEFORE fsdevMountSdmc() — unlike
    // BtWrite which needs the libnx-mounted sdmc. Each call opens+writes+closes its
    // own session so it survives a hang on the very next line. Purpose: locate
    // exactly where a 2nd-in-session uMenu relaunch parks (its boot-trace is empty
    // = it dies before its first mounted-sdmc write). Reading umenu_early_trace.log:
    //   file ABSENT          -> parked in crt0/__libnx_init/smInitialize/fsInitialize
    //   "(a)" present, no BT  -> parked IN fsdevMountSdmc
    //   "(a)"+"(b)", no BT    -> parked in the boot-trace setup block (264-281)
    //   BT present            -> parked later (see umenu_boot_trace.log)
    static void EarlyTrace(const char *tag) {
        FsFileSystem fs;
        if(R_FAILED(fsOpenSdCardFileSystem(&fs))) return;
        fsFsCreateDirectory(&fs, "/ulaunch");                          // idempotent
        fsFsCreateFile(&fs, "/ulaunch/umenu_early_trace.log", 0, 0);   // idempotent
        FsFile file;
        if(R_SUCCEEDED(fsFsOpenFile(&fs, "/ulaunch/umenu_early_trace.log",
                                    FsOpenMode_Write | FsOpenMode_Append, &file))) {
            s64 sz = 0;
            fsFileGetSize(&file, &sz);
            char line[160];
            const int n = snprintf(line, sizeof(line), "[EARLY] %s\n", tag);
            if(n > 0) {
                fsFileWrite(&file, sz, line, (u64)n, FsWriteOption_Flush);
            }
            fsFileClose(&file);
        }
        fsFsClose(&fs);
    }

    void __appInit() {
        UL_RC_ASSERT(smInitialize());

        UL_RC_ASSERT(fsInitialize());
        EarlyTrace("(a) fsInitialize OK — pre-fsdevMountSdmc");
        UL_RC_ASSERT(fsdevMountSdmc());
        EarlyTrace("(b) fsdevMountSdmc OK");

        // v2.0.3-A3: ensure sdmc:/switch/ exists at boot. HBmenu currently
        // creates this directory on first run; once HBmenu is removed (P-07
        // in the HBmenu deletion checklist), uMenu must own the create.
        // Idempotent: EEXIST on populated SD ~0.5-1ms; ignored.
        mkdir("sdmc:/switch/", 0777);

        // BOOT-TRACE: arm the flag once sdmc is mounted so every subsequent
        // BtWrite call can open the log.  access() is safe at this point.
        // The flag file is sdmc:/ulaunch/debug.flag (same dev-mode gate used
        // by uSystem's HomeTrace and uMenu's dev-mode paths).
        {
            mkdir("sdmc:/ulaunch", 0777);   // idempotent
            g_bt_enabled = (access("sdmc:/ulaunch/debug.flag", F_OK) == 0);
            if (g_bt_enabled) {
                // Stamp the trace file with a boot separator so successive
                // reboots don't blur together.
                FILE *f = fopen("sdmc:/ulaunch/umenu_boot_trace.log", "ab");
                if (f) {
                    const char sep[] = "\n--- uMenu __appInit ENTRY ---\n";
                    fwrite(sep, sizeof(sep) - 1, 1, f);
                    fclose(f);
                }
            }
        }
        BT("__appInit ENTRY — smInitialize+fsdevMountSdmc OK");

        UL_RC_ASSERT(timeInitialize());
        __libnx_init_time();
        BT("timeInitialize OK");

        ul::InitializeLogging("uMenu");
        ul::tel::Init("uMenu");
        BT("InitializeLogging + tel::Init OK");
        // Flush the async SPSC telemetry queue on normal C-library exit (covers
        // the Home-button-press-from-library-applet path which calls C atexit
        // handlers before __appExit).  Crashes that skip atexit still get
        // synchronous WARN/CRIT entries via EmitSync; BOOT markers are already
        // written synchronously in tel::Init.  This captures best-effort INFO
        // messages accumulated since the last periodic flush.
        std::atexit([] { ul::tel::Flush(); });
        UL_LOG_INFO("Alive!");

        UL_RC_ASSERT(setsysInitialize());
        g_svc_lh_setsys_ = UL_LEDGER_TRACK(
            ::ul::menu::qdesktop::QdResKind::Service, "main:setsys", 0);
        UL_RC_ASSERT(setInitialize());

        UL_RC_ASSERT(setsysGetFirmwareVersion(&g_FirmwareVersion));
        hosversionSet(MAKEHOSVERSION(g_FirmwareVersion.major, g_FirmwareVersion.minor, g_FirmwareVersion.micro) | BIT(31));

        // W18-RACE-RETRY: appletInitialize() can return svc::SessionClosed
        // (0xF601 / 2001-0123) when the previous uMenu session crashed without
        // cleanly releasing the SystemApplet session.  Atmosphère's am
        // sysmodule needs a few hundred milliseconds to re-establish the
        // session in that case.  A plain UL_RC_ASSERT here panics on the
        // very next boot after any crash and leaves the user with a black
        // screen until they hard power-cycle.  Retry up to 8 times with
        // 100 ms backoff before giving up — gives am ~800 ms to recover.
        BT("BEFORE appletInitialize (retry loop)");
        {
            Result rc_applet = 0;
            for (int i = 0; i < 8; ++i) {
                rc_applet = appletInitialize();
                if (R_SUCCEEDED(rc_applet)) break;
                UL_LOG_WARN("appletInitialize attempt %d/%d rc=0x%08X — "
                            "retrying in 100ms",
                            i + 1, 8, rc_applet);
                svcSleepThread(100'000'000ULL);  // 100 ms
            }
            UL_RC_ASSERT(rc_applet);
        }
        BT("appletInitialize OK");
        // v2.0.3-A1 first-paint telemetry: capture tick immediately after
        // appletInitialize() so the t_appinit -> first-paint delta excludes
        // pre-applet libnx setup (sm/fs/time) which is invariant across boots.
        g_qos_boot_t_appinit_ticks = armGetSystemTick();
        BT("BEFORE hidInitialize");
        UL_RC_ASSERT(hidInitialize());
        BT("hidInitialize OK");

        // W18-RACE-RETRY: same protection for ns + account — those are the
        // other sysmodule sessions that can be transitionally closed in the
        // same crash-recovery window.
        BT("BEFORE accountInitialize (retry loop)");
        {
            Result rc_acc = 0;
            for (int i = 0; i < 8; ++i) {
                rc_acc = accountInitialize(AccountServiceType_System);
                if (R_SUCCEEDED(rc_acc)) break;
                UL_LOG_WARN("accountInitialize attempt %d/%d rc=0x%08X",
                            i + 1, 8, rc_acc);
                svcSleepThread(100'000'000ULL);
            }
            UL_RC_ASSERT(rc_acc);
        }
        BT("accountInitialize OK");
        g_svc_lh_account_ = UL_LEDGER_TRACK(
            ::ul::menu::qdesktop::QdResKind::Service, "main:account", 0);
        // W18-RACE-RETRY: ns can also hit SessionClosed in the same window.
        BT("BEFORE nsInitialize (retry loop)");
        {
            Result rc_ns = 0;
            for (int i = 0; i < 8; ++i) {
                rc_ns = nsInitialize();
                if (R_SUCCEEDED(rc_ns)) break;
                UL_LOG_WARN("nsInitialize attempt %d/%d rc=0x%08X",
                            i + 1, 8, rc_ns);
                svcSleepThread(100'000'000ULL);
            }
            UL_RC_ASSERT(rc_ns);
        }
        BT("nsInitialize OK");
        g_svc_lh_ns_ = UL_LEDGER_TRACK(
            ::ul::menu::qdesktop::QdResKind::Service, "main:ns", 0);
        BT("BEFORE nssuInitialize");
        UL_RC_ASSERT(nssuInitialize());
        BT("BEFORE avmInitialize");
        UL_RC_ASSERT(avmInitialize());
        BT("BEFORE ul::net::Initialize");
        UL_RC_ASSERT(ul::net::Initialize());
        BT("BEFORE psmInitialize");
        UL_RC_ASSERT(psmInitialize());
        BT("psmInitialize OK");
        g_svc_lh_psm_ = UL_LEDGER_TRACK(
            ::ul::menu::qdesktop::QdResKind::Service, "main:psm", 0);

        ul::menu::SetControlEntryLoadFunction(MenuControlEntryLoadFunction);
        BT("BEFORE bt::InitializeBluetoothManager");
        ul::menu::bt::InitializeBluetoothManager();
        BT("bt::InitializeBluetoothManager OK");

        // v3.1 Phase 2 Task 6's `viInitialize(Manager)` was REMOVED 2026-05-19
        // per uMenu audit F5.3.  Original intent: claim vi:m before
        // __nx_win_init so the BG-indirect probe could use vi:m-only
        // primitives.  We pivoted that capture path to a uSystem-owned
        // Tesla-style overlay (Tesla overlay model — see CHANGELOG v3.0.2),
        // so uMenu no longer needs vi:m.  Letting libnx's __nx_win_init pick
        // the default service type per applet kind saves 1–3 ms of IPC on
        // every boot (and avoids the vi:m permission-denial retry on HW
        // where the cap isn't granted).
        //
        // If a future feature in uMenu needs vi:m, re-add a viInitialize call
        // here BEFORE __nx_win_init (libnx's vi globals are sticky on first
        // init).

        // NRO-RELAUNCH VI-LAYER FIX (2026-06-19):
        //
        // When uMenu is relaunched after a library-applet NRO exits, the
        // compositor tears down the NRO's vi layer asynchronously.  If the NRO
        // was itself a library applet (the second-applet case), the compositor
        // may not have freed the managed-layer slot by the time __nx_win_init()
        // runs.  libnx's __nx_win_init calls viInitialize(System) then
        // viCreateManagedLayer + nwindowCreateFromLayer and throws a fatal
        // LibnxError_BadGfxInit if viCreateManagedLayer fails.
        //
        // On a CLEAN boot uMenu is the first library applet so the compositor
        // slot is always free — no hang.  On NRO-relaunch the slot may still
        // be in teardown (observed: ~80–500 ms on Erista), causing
        // viCreateManagedLayer inside __nx_win_init to block until the slot is
        // freed OR return an error that libnx escalates to a fatal.
        //
        // uSystem's 500 ms settle sleep (uSystem main.cpp:1783) usually covers
        // the teardown window, but the compositor can still be draining when
        // uMenu's __appInit fires because __appInit runs during ECS launch
        // registration, BEFORE the compositor acknowledges the new applet.
        //
        // DIAGNOSTIC STRATEGY: trace BEFORE and AFTER __nx_win_init so the
        // boot-trace log shows whether the hang is inside __nx_win_init (most
        // likely) or elsewhere.  If the hang IS inside __nx_win_init, the
        // "AFTER" line will never appear on a relaunch-black test.
        //
        // FIX ATTEMPT: pre-probe viInitialize(System) before __nx_win_init so
        // we can log an explicit vi result code rather than hitting the libnx
        // fatal handler (which writes nothing to our trace log).  If
        // viInitialize succeeds, proceed.  viInitialize is idempotent if the
        // service was already open (libnx tracks a global open count), so
        // __nx_win_init calling it again internally is safe.  This probe does
        // NOT retry — it only informs the trace; the retry logic is in uSystem.
        BT("BEFORE viInitialize(System) probe");
        {
            const Result vi_rc = viInitialize(ViServiceType_System);
            char vi_buf[64];
            ::snprintf(vi_buf, sizeof(vi_buf),
                "viInitialize(System) probe rc=0x%08X", vi_rc);
            BT(vi_buf);
            // If the probe succeeded we now hold one extra reference.
            // Close it immediately — __nx_win_init opens its own reference
            // and we must not interfere with its refcount management.
            if (R_SUCCEEDED(vi_rc)) {
                viExit();
                BT("viExit() (probe ref released)");
            }
        }

        BT("BEFORE __nx_win_init (vi managed-layer creation)");
        __nx_win_init();
        BT("__nx_win_init RETURNED OK — display layer acquired");
    }

    void __appExit() {
        // W7: flush and close the perf log before any service teardown so the
        // final rows land on disk before sdmc: is unmounted.
        ::ul::menu::qdesktop::QdPerfLogger::Instance().Shutdown();

        // W6-LEDGER: untrack process-lifetime services before they exit.
        UL_LEDGER_UNTRACK(g_svc_lh_psm_);     g_svc_lh_psm_     = 0;
        UL_LEDGER_UNTRACK(g_svc_lh_ns_);      g_svc_lh_ns_      = 0;
        UL_LEDGER_UNTRACK(g_svc_lh_account_); g_svc_lh_account_ = 0;
        UL_LEDGER_UNTRACK(g_svc_lh_setsys_);  g_svc_lh_setsys_  = 0;
        ul::tel::Shutdown();

        ul::audio::FinalizeSystemVolume();
        ul::menu::smi::sf::FinalizePrivateService();

        // Exit RomFs manually, since we also initialized it manually
        romfsExit();

        UL_LOG_INFO("Goodbye!");

        __nx_win_exit();

        ul::menu::bt::FinalizeBluetoothManager();
        setExit();
        setsysExit();
        psmExit();
        ul::net::Finalize();
        avmExit();
        nssuExit();
        nsExit();
        accountExit();

        timeExit();

        hidExit();

        appletExit();

        fsdevUnmountAll();
        fsExit();

        smExit();
    }

}

ul::menu::ui::MenuApplication::Ref g_MenuApplication;

namespace {

    ul::smi::MenuStartMode g_StartMode;

    void InitializeSettings() {
        UL_LOG_INFO("Initializing settings...");
        g_GlobalSettings = {};

        UL_RC_ASSERT(timeGetDeviceLocationName(&g_GlobalSettings.timezone));

        ul::os::GetAmsConfig(g_GlobalSettings.ams_version, g_GlobalSettings.ams_is_emummc);
        g_GlobalSettings.fw_version = g_FirmwareVersion;

        UL_RC_ASSERT(setsysGetSerialNumber(&g_GlobalSettings.serial_no));
        UL_RC_ASSERT(setsysGetSleepSettings(&g_GlobalSettings.sleep_settings));
        UL_RC_ASSERT(setGetRegionCode(&g_GlobalSettings.region));
        UL_RC_ASSERT(setsysGetPrimaryAlbumStorage(&g_GlobalSettings.album_storage));
        UL_RC_ASSERT(setsysGetNfcEnableFlag(&g_GlobalSettings.nfc_enabled));
        UL_RC_ASSERT(setsysGetUsb30EnableFlag(&g_GlobalSettings.usb30_enabled));
        UL_RC_ASSERT(setsysGetBluetoothEnableFlag(&g_GlobalSettings.bluetooth_enabled));
        UL_RC_ASSERT(setsysGetWirelessLanEnableFlag(&g_GlobalSettings.wireless_lan_enabled));
        UL_RC_ASSERT(setsysGetAutoUpdateEnableFlag(&g_GlobalSettings.auto_update_enabled));
        UL_RC_ASSERT(setsysGetAutomaticApplicationDownloadFlag(&g_GlobalSettings.auto_app_download_enabled));
        UL_RC_ASSERT(setsysGetConsoleInformationUploadFlag(&g_GlobalSettings.console_info_upload_enabled));

        u64 lang_code;
        UL_RC_ASSERT(setGetSystemLanguage(&lang_code));
        UL_RC_ASSERT(setMakeLanguage(lang_code, &g_GlobalSettings.language));

        s32 tmp;
        UL_RC_ASSERT(setGetAvailableLanguageCodes(&tmp, g_GlobalSettings.available_language_codes, ul::os::LanguageNameCount));

        UL_RC_ASSERT(setsysGetDeviceNickname(&g_GlobalSettings.nickname));
        UL_RC_ASSERT(setsysGetBatteryLot(&g_GlobalSettings.battery_lot));

        // v1.8.10: pull system theme colour preference once at startup.
        // appletInitialize() runs in __appInit before InitializeSettings, so
        // appletGetThemeColorType() is safe to call here.  The libnx function
        // returns the AppletThemeColorType value directly (not via Result+pointer),
        // so we assign it unconditionally; on any unexpected state libnx returns
        // AppletThemeColorType_Default (0) which is a safe sentinel.
        g_GlobalSettings.theme_color_type = appletGetThemeColorType();
        UL_LOG_INFO("InitializeSettings: theme_color_type=%d", static_cast<int>(g_GlobalSettings.theme_color_type));
    }

    void MainLoop() {
        // Load menu config
        g_GlobalSettings.config = ul::cfg::LoadConfig();

        // v3.5.1 stable: canonical synchronous EnsureQosThemesOnSd.
        //
        // The v3.5.0 W17-FIX2 attempt to move this to a detached background
        // thread caused a deterministic infinite-relaunch loop on HW: the
        // bg-thread + main-thread fsdev contention silently aborted the main
        // thread's progress before MenuApplication::Load() — uMenu exited
        // clean within ~50 ms of boot, uSystem's "previous launch failure"
        // recovery (uSystem main.cpp:1541) relaunched immediately, infinite
        // black screen.  Reverting to v3.4.0's synchronous path costs at
        // worst ~120 ms on the first boot after a theme bundle changes (and
        // 0 ms on every subsequent boot when sizes match) — well below
        // perceptual threshold and worth a billion times the stability.
        //
        // The bg-thread refactor returns in v3.6 only after we have a real
        // SD-card lock-arbitration primitive (the v1.8.15 prewarm thread
        // pattern works because Plutonium owns the renderer mutex; theme
        // bundles touch sdmc files that the main thread's log writer ALSO
        // hits via UL_LOG_INFO → LogImpl → fopen("ab+")).
        const bool qos_themes_refreshed = EnsureQosThemesOnSd();
        if (qos_themes_refreshed) {
            UL_LOG_INFO("main: Q OS theme bundles refreshed — invalidating cache");
            ul::cfg::RemoveActiveThemeCache();
        }
        g_qos_themes_bg_done.store(true, std::memory_order_release);

        // W12-LAZYTHEME Phase 1: populate metadata for all 10 theme packs from
        // in-binary tables (no I/O, no zip, no SDL). This is the ONLY boot-time
        // operation across all 10 themes. ~2 KiB total, < 1 µs.
        ul::menu::qdesktop::QdLazyLoader::LoadAllThemeMetadata();

        // v2.4.0: apply persisted in-binary theme pack as a FALLBACK default
        // for when no .ultheme is active. The actual theme palette comes from
        // the .ultheme's ui/QdPalette.json (read via LoadThemeFromCache below
        // after TryLoadTheme). This early call ensures g_QdTheme has sane
        // values for the very first frame of rendering if .ultheme load
        // takes any time. v2.7.0: the qos-folder-theme.toml entry is now a
        // back-compat default; the .ultheme is the canonical persistence.
        //
        // W12-LAZYTHEME Phase 2: use LoadThemeAssets() for the active pack so
        // the new two-phase API is the single load path. Wallpaper pack is
        // loaded separately (it can differ from the palette pack).
        {
            // v3.1.1 — palette/folder-theme pack and wallpaper pack are now
            // persisted independently (qos-folder-theme.toml vs qos-wallpaper.toml).
            // Load both at boot.  qos-wallpaper.toml's loader falls back to
            // the folder-theme value if the file is absent, preserving the
            // pre-3.1.1 unified selection on upgrade.
            const size_t persisted_palette   = ul::menu::qdesktop::LoadActiveThemePack();
            const size_t persisted_wallpaper = ul::menu::qdesktop::LoadActiveWallpaperPack();
            // W12: LoadThemeAssets handles palette + wallpaper dirty-flag +
            // PNG cache. Then we separately set the wallpaper pack (which may
            // differ from the palette pack) and re-raise the dirty flag.
            ul::menu::qdesktop::QdLazyLoader::LoadThemeAssets(persisted_palette);
            ul::menu::qdesktop::SetActiveWallpaperPack(persisted_wallpaper);
            const size_t persisted = persisted_palette;  // backward-compat alias for the log below
            UL_LOG_INFO("main: W12 boot LoadThemeAssets(%zu) + wallpaper_pack=%zu "
                        "g_QdTheme.accent=#%02X%02X%02X g_QdTheme.desktop_bg=#%02X%02X%02X",
                        persisted,
                        ul::menu::qdesktop::g_active_wallpaper_pack,
                        ul::menu::qdesktop::g_QdTheme.accent.r,
                        ul::menu::qdesktop::g_QdTheme.accent.g,
                        ul::menu::qdesktop::g_QdTheme.accent.b,
                        ul::menu::qdesktop::g_QdTheme.desktop_bg.r,
                        ul::menu::qdesktop::g_QdTheme.desktop_bg.g,
                        ul::menu::qdesktop::g_QdTheme.desktop_bg.b);
        }

        // Cache active theme, if needed
        if(g_GlobalSettings.system_status.reload_theme_cache) {
            ul::cfg::CacheActiveTheme(g_GlobalSettings.config);
        }

        UL_ASSERT_TRUE(g_GlobalSettings.config.GetEntry(ul::cfg::ConfigEntryId::HomebrewApplicationTakeoverApplicationId, g_GlobalSettings.cache_hb_takeover_app_id));

        // Load active theme, if set
        std::string active_theme_name;
        Result active_theme_load_rc = ul::ResultSuccess;
        UL_ASSERT_TRUE(g_GlobalSettings.config.GetEntry(ul::cfg::ConfigEntryId::ActiveThemeName, active_theme_name));
        if(!active_theme_name.empty()) {
            const auto rc = ul::cfg::TryLoadTheme(active_theme_name, g_GlobalSettings.active_theme);
            if(R_SUCCEEDED(rc)) {
                ul::cfg::EnsureCacheActiveTheme(g_GlobalSettings.config);
                // v2.7.0 — read the .ultheme's ui/QdPalette.json into g_QdTheme
                // (and read its wallpaper_pack hint into g_active_wallpaper_pack).
                // This is the SINGLE point at which the active .ultheme drives
                // the qdesktop palette. Without this call, picking a Q OS
                // .ultheme via the Themes menu apply path correctly persists
                // the active_theme_name but the palette + wallpaper_pack don't
                // refresh on next boot — they'd stay at the in-binary fallback.
                ul::menu::qdesktop::LoadThemeFromCache(ul::ActiveThemeCachePath);
                // v3.1.2 BUG-10b extra: LoadThemeFromCache reads
                // wallpaper_pack from the active theme's QdPalette.json,
                // which is the THEME'S intended wallpaper.  But the user
                // may have picked a DIFFERENT wallpaper via the empty-
                // desktop ZL menu (qos-wallpaper.toml).  User choice wins
                // — re-apply the persisted_wallpaper already loaded from
                // qos-wallpaper.toml above (same file, no second disk read).
                // W8-FIX Bug 6: also persist the final wallpaper pack
                // immediately so a homebrew-exit restart re-applies the
                // correct value even if the user never explicitly used
                // "Change Wallpaper" in this session.
                {
                    // (A1-OPT-3 reverted: persisted_wallpaper from the outer block
                    // is out of scope here; the second load is cheap + correct.)
                    const size_t user_wallpaper = ul::menu::qdesktop::LoadActiveWallpaperPack();
                    ul::menu::qdesktop::SetActiveWallpaperPack(user_wallpaper);
                    // v3.7 COHESION (Option A): the palette is owned by the active
                    // icon THEME (LoadThemeFromCache above already applied the
                    // bundle's QdPalette.json).  The wallpaper is only the
                    // independent background IMAGE — do NOT override the palette
                    // from it, so icons + window + accent stay one coherent look.
                    ul::menu::qdesktop::SaveActiveWallpaperPack(user_wallpaper);
                }
                UL_LOG_INFO("main: post-LoadThemeFromCache + user-wallpaper-restore "
                            "g_active_wallpaper_pack=%zu accent=#%02X%02X%02X",
                            ul::menu::qdesktop::g_active_wallpaper_pack,
                            ul::menu::qdesktop::g_QdTheme.accent.r,
                            ul::menu::qdesktop::g_QdTheme.accent.g,
                            ul::menu::qdesktop::g_QdTheme.accent.b);
            }
            else {
                g_GlobalSettings.active_theme = {};
                UL_LOG_WARN("Unable to load active theme '%s': %s, resetting to default theme...", active_theme_name.c_str(), ul::util::FormatResultDisplay(rc).c_str());
                UL_ASSERT_TRUE(g_GlobalSettings.config.SetEntry(ul::cfg::ConfigEntryId::ActiveThemeName, g_GlobalSettings.active_theme.name));
                g_GlobalSettings.SaveConfig();
                ul::cfg::RemoveActiveThemeCache();
                active_theme_load_rc = rc;
            }
        }
        else {
            UL_LOG_INFO("No active theme set...");
            // W8-FIX Bug 6 (no-theme path): persist the wallpaper pack
            // loaded from TOML so the file always exists and homebrew-
            // exit restart re-reads the correct value.
            ul::menu::qdesktop::SaveActiveWallpaperPack(
                ul::menu::qdesktop::g_active_wallpaper_pack);
        }

        // List added/removed/in verify applications
    
        UL_LOG_INFO("Added app count: %d", g_GlobalSettings.system_status.last_added_app_count);
        if(g_GlobalSettings.system_status.last_added_app_count > 0) {
            auto app_buf = new u64[g_GlobalSettings.system_status.last_added_app_count]();
            UL_RC_ASSERT(ul::menu::smi::ListAddedApplications(g_GlobalSettings.system_status.last_added_app_count, app_buf));
            for(u32 i = 0; i < g_GlobalSettings.system_status.last_added_app_count; i++) {
                UL_LOG_INFO("> Added app: 0x%016lX", app_buf[i]);
                g_GlobalSettings.added_app_ids.push_back(app_buf[i]);
            }
            delete[] app_buf;
        }

        UL_LOG_INFO("Deleted app count: %d", g_GlobalSettings.system_status.last_deleted_app_count);
        if(g_GlobalSettings.system_status.last_deleted_app_count > 0) {
            auto app_buf = new u64[g_GlobalSettings.system_status.last_deleted_app_count]();
            UL_RC_ASSERT(ul::menu::smi::ListDeletedApplications(g_GlobalSettings.system_status.last_deleted_app_count, app_buf));
            for(u32 i = 0; i < g_GlobalSettings.system_status.last_deleted_app_count; i++) {
                UL_LOG_INFO("> Deleted app: 0x%016lX", app_buf[i]);

                if(g_GlobalSettings.cache_hb_takeover_app_id == app_buf[i]) {
                    g_GlobalSettings.ResetHomebrewTakeoverApplicationId();
                }

                g_GlobalSettings.deleted_app_ids.push_back(app_buf[i]);
            }
            delete[] app_buf;
        }

        UL_LOG_INFO("In verify app count: %d", g_GlobalSettings.system_status.in_verify_app_count);
        if(g_GlobalSettings.system_status.in_verify_app_count > 0) {
            auto app_buf = new u64[g_GlobalSettings.system_status.in_verify_app_count]();
            UL_RC_ASSERT(ul::menu::smi::ListInVerifyApplications(g_GlobalSettings.system_status.in_verify_app_count, app_buf));
            for(u32 i = 0; i < g_GlobalSettings.system_status.in_verify_app_count; i++) {
                UL_LOG_INFO("> App being verified: 0x%016lX", app_buf[i]);
                g_GlobalSettings.in_verify_app_ids.push_back(app_buf[i]);
            }
            delete[] app_buf;
        }

        // Get system language and load translations (default one if not present)
        ul::cfg::LoadLanguageJsons(ul::MenuLanguagesPath, g_GlobalSettings.main_lang, g_GlobalSettings.default_lang);

        BT("MainLoop: BEFORE RendererInitOptions build");
        auto renderer_opts = pu::ui::render::RendererInitOptions(SDL_INIT_EVERYTHING, pu::ui::render::RendererHardwareFlags);
        renderer_opts.SetPlServiceType(PlServiceType_User);
        renderer_opts.SetInputPlayerCount(8);
        renderer_opts.AddInputNpadStyleTag(HidNpadStyleSet_NpadStandard);
        renderer_opts.AddInputNpadIdType(HidNpadIdType_Handheld);
        renderer_opts.AddInputNpadIdType(HidNpadIdType_No1);
        renderer_opts.AddInputNpadIdType(HidNpadIdType_No2);
        renderer_opts.AddInputNpadIdType(HidNpadIdType_No3);
        renderer_opts.AddInputNpadIdType(HidNpadIdType_No4);
        renderer_opts.AddInputNpadIdType(HidNpadIdType_No5);
        renderer_opts.AddInputNpadIdType(HidNpadIdType_No6);
        renderer_opts.AddInputNpadIdType(HidNpadIdType_No7);
        renderer_opts.AddInputNpadIdType(HidNpadIdType_No8);

        const auto default_font_path = ul::menu::ui::TryGetActiveThemeResource("ui/Font.ttf");
        if(!default_font_path.empty()) {
            // v3.7 visual overhaul: Space Grotesk (Basic Latin + Latin-1) as the
            // PRIMARY UI face.  Added first so it wins the fallback chain for
            // ASCII/Latin glyphs.
            renderer_opts.AddDefaultFontPath(default_font_path);
        }
        // v3.7: ALWAYS register the Nintendo shared fonts AFTER any custom face
        // so they serve as FALLBACKS — the custom Latin font renders ASCII/Latin,
        // while CJK game titles, Korean, and extended symbols still resolve
        // instead of showing tofu.  (Previously these loaded ONLY when no custom
        // font was set, which would have broken CJK the moment Font.ttf shipped.)
        renderer_opts.AddDefaultSharedFont(PlSharedFontType_Standard);
        renderer_opts.AddDefaultSharedFont(PlSharedFontType_ChineseSimplified);
        renderer_opts.AddDefaultSharedFont(PlSharedFontType_ExtChineseSimplified);
        renderer_opts.AddDefaultSharedFont(PlSharedFontType_ChineseTraditional);
        renderer_opts.AddDefaultSharedFont(PlSharedFontType_KO);
        renderer_opts.AddDefaultSharedFont(PlSharedFontType_NintendoExt);
        renderer_opts.UseImage(pu::ui::render::ImgAllFlags);

        // Cycle J-fix: register extra small font sizes so RenderTextAutoFit
        // (in ui_Common.hpp) can shrink long icon labels and account names
        // below Plutonium's built-in 27 px Small floor before they hit the
        // ellipsis-truncation branch in render_Renderer.cpp:375. Without
        // these, "Pokemon Legends: Z-A" can't fit in a 120 px icon cell at
        // any built-in size and Plutonium chops to "Pokemon Lege..." which
        // the user reported in the J-cycle test.
        renderer_opts.AddExtraDefaultFontSize(22);
        renderer_opts.AddExtraDefaultFontSize(18);
        renderer_opts.AddExtraDefaultFontSize(14);

        // BOOT-TRACE: Renderer::New drives SDL_Init → SDL_CreateWindow →
        // SDL_CreateRenderer internally.  These trace points bracket that
        // call so the log shows whether SDL init itself hangs (e.g. because
        // nwindowGetDefault() blocks inside SDL_nx.c waiting for a vi buffer
        // slot that the compositor hasn't released yet).
        BT("MainLoop: BEFORE Renderer::New (SDL_Init + SDL_CreateWindow + SDL_CreateRenderer)");
        auto renderer = pu::ui::render::Renderer::New(renderer_opts);
        BT("MainLoop: Renderer::New RETURNED");

        BT("MainLoop: BEFORE MenuApplication::New");
        g_MenuApplication = ul::menu::ui::MenuApplication::New(renderer);
        BT("MainLoop: MenuApplication::New RETURNED");

        // W7: initialise perf logger now that sdmc: is mounted and renderer exists.
        // sdmc:/ulaunch/ is created by __appInit's mkdir("sdmc:/switch/") chain;
        // the logger creates its own file with fopen("a") which is safe regardless.
        ::ul::menu::qdesktop::QdPerfLogger::Instance().Init();

        BT("MainLoop: BEFORE pu::audio::Initialize");
        UL_ASSERT_TRUE(pu::audio::Initialize(MIX_INIT_MP3));
        ul::audio::InitializeSystemVolume();
        BT("MainLoop: audio initialized");

        BT("MainLoop: BEFORE g_MenuApplication->Initialize");
        g_MenuApplication->Initialize(g_StartMode);
        BT("MainLoop: g_MenuApplication->Initialize RETURNED");
        ul::menu::ui::RegisterMenuOnMessageDetect();
        BT("MainLoop: BEFORE InitializePrivateService");
        UL_RC_ASSERT(ul::menu::smi::sf::InitializePrivateService());
        BT("MainLoop: InitializePrivateService OK — debug-server starts after Load()");

#ifdef QDESKTOP_MODE
        // HOME-FROM-APP BLACK-SCREEN FIX (2026-06-19):
        //
        // When uMenu is relaunched by uSystem after the user presses HOME
        // from a running application (MainMenu / mode 3), the compositor does
        // NOT automatically transfer foreground to uMenu.  uSystem called
        // sys::SetForeground() before launching uMenu, but the ECS applet
        // handoff leaves uMenu in Background applet-focus: the compositor
        // keeps presenting either the suspended app's framebuffer or nothing,
        // and uMenu's frames go unseen — permanent black screen.
        //
        // The per-frame appletRequestToGetForeground() loop added in v3.7.2
        // (qd_AppletLifecycle.cpp PumpAppletMessages) handles this AFTER the
        // render loop starts.  But for MainMenu mode the render loop doesn't
        // start until AFTER Load() which runs InitializeEntries() — a
        // synchronous NS IPC call that can block for several seconds while
        // the exiting game process is still alive in AM.  During that window
        // the screen stays black and PumpAppletMessages never fires.
        //
        // Fix: call appletRequestToGetForeground() BEFORE Load()/Show() for
        // all non-Startup modes so the kernel starts the foreground handoff
        // while InitializeEntries() / theme loading is running.  Startup modes
        // (StartupMenu, StartupMenuPostBoot) are excluded because they must
        // remain in the background until the user selects a user account
        // (same behaviour as before v3.7.2).
        //
        // This call is best-effort (ignore return value) — it may return an
        // IPC error while AM is settling after app termination; the per-frame
        // loop in PumpAppletMessages is the authoritative retry path.
        if (g_StartMode != ul::smi::MenuStartMode::StartupMenu &&
            g_StartMode != ul::smi::MenuStartMode::StartupMenuPostBoot) {
            (void)appletRequestToGetForeground();
            UL_LOG_INFO("main: early appletRequestToGetForeground for start_mode=%u",
                        static_cast<u32>(g_StartMode));
        }
#endif

        // W7: register perf logger frame hooks as render callbacks.
        // Callback order per CallForRender: render_cbs fire first (before layout
        // element render), so we call OnFrameEnd() to close the previous frame
        // and OnFrameBegin() to start the current frame in a single callback.
        // This gives frame_ms = inter-callback interval (≈ full frame period)
        // and render_ms ≈ 0 (the callback fires before Plutonium's render pass).
        g_MenuApplication->AddRenderCallback([]() {
            auto &perf = ::ul::menu::qdesktop::QdPerfLogger::Instance();
            perf.OnFrameEnd();    // close previous frame / write row if due
            perf.OnFrameBegin();  // start current frame tick
        });

#ifdef QDESKTOP_MODE
        // v2.8.3 — register applet sleep/wake hook so the shell + nxlink
        // servers get a clean Stop() call when the Switch sleeps or uMenu
        // loses focus.  Without this, the servers stayed running across
        // sleep, their listen sockets got invalidated by WiFi disconnect,
        // and accept() spun on ECONNABORTED until log fsync starved the UI
        // thread.  See qd_AppletLifecycle.hpp for the full design notes.
        //
        // Must be registered AFTER InitializePrivateService (we depend on
        // the smi server's session being live for any logging from the
        // hook callback) and BEFORE Load() (so the hook is armed before
        // any frame paints — the first frame can trigger applet messages).
        ul::menu::qdesktop::RegisterAppletHooks();

        // v2.8.4 — Plutonium's ui_Application::Show() is a tight
        // CallForRender loop with NO appletMainLoop() call (confirmed by
        // background-agent audit 2026-05-18: Plutonium/source/pu/ui/ui_Application.cpp:247-256).
        // Without an explicit pump, the hook registered above never fires
        // — the message queue stays full forever.  Register PumpAppletMessages
        // as a render callback so it runs once per frame on the main thread,
        // draining the queue and dispatching focus/resume/exit hooks.
        //
        // This matches the pattern already used by ui_MenuApplication.cpp:343
        // and :408 for the BGM-volume + chrome-terminate render callbacks.
        // Cost: ~50µs per frame, <0.5% of frame budget.
        g_MenuApplication->AddRenderCallback(&ul::menu::qdesktop::PumpAppletMessages);
#endif
        BT("MainLoop: BEFORE g_MenuApplication->Load()");
        UL_RC_ASSERT(g_MenuApplication->Load());
        BT("MainLoop: g_MenuApplication->Load() RETURNED");

        // Initialize uSystem message handling (need to do it after Load so that the message handlers are registered)
        // UL_RC_ASSERT(ul::menu::smi::sf::InitializePrivateService());

        if(R_FAILED(active_theme_load_rc)) {
            g_MenuApplication->NotifyActiveThemeLoadFailure(active_theme_load_rc);
        }
        if(g_GlobalSettings.active_theme.IsValid() && g_GlobalSettings.active_theme.IsOutdated()) {
            g_MenuApplication->NotifyActiveThemeOutdated();
        }

        // v3.1 Phase 1/2 probes removed 2026-05-19 — architectural conclusion
        // captured in docs/archive/ (caps:sc returns rc=0xE0CE; viGetIndirect-
        // LayerImageMap returns 2114-0011 due to handle-ownership check that
        // can't be bypassed from a SystemApplet).  Pivot to Tesla-style
        // overlay layer owned by uSystem — see docs/50_v3.1_phase2_*.

#ifdef QDESKTOP_MODE
        // POST-LOAD FOREGROUND RE-ASSERT (2026-06-19):
        //
        // Load() above runs InitializeEntries() — a synchronous NS IPC call that
        // iterates all installed titles and can block for 1–4 seconds.  During that
        // window the compositor may time out the pending foreground handoff that the
        // early appletRequestToGetForeground() (above, before Load) initiated.  If
        // the handoff expires, the compositor keeps presenting nothing (black screen)
        // and the single per-frame PumpAppletMessages loop can't recover because the
        // OS only processes one foreground-grant per compositor frame cycle — if
        // uMenu has been out of focus since it launched, the first few frames of
        // Show() go to a surface the compositor doesn't present.
        //
        // Fix: after Load() returns, re-assert foreground with a short busy-retry
        // loop (5 × 30ms = up to 150ms) for all non-Startup modes.  Each call is
        // non-blocking; we just need AM to queue the foreground-transfer IPC command
        // before Show() starts rendering.  The per-frame PumpAppletMessages remains
        // the authoritative ongoing handler — this burst is only the bridge between
        // "Load() blocked" and "first frame presented".
        if (g_StartMode != ul::smi::MenuStartMode::StartupMenu &&
            g_StartMode != ul::smi::MenuStartMode::StartupMenuPostBoot) {
            UL_LOG_INFO("main: post-Load foreground re-assert burst for start_mode=%u",
                        static_cast<u32>(g_StartMode));
            for (int fg_retry = 0; fg_retry < 5; ++fg_retry) {
                (void)appletRequestToGetForeground();
                svcSleepThread(30'000'000ul);   // 30 ms between retries
            }
            UL_LOG_INFO("main: post-Load foreground re-assert burst complete");
        }
#endif

        if(g_StartMode == ul::smi::MenuStartMode::StartupMenuPostBoot) {
            BT("MainLoop: BEFORE g_MenuApplication->ShowWithFadeIn()");
            g_MenuApplication->ShowWithFadeIn();
            BT("MainLoop: ShowWithFadeIn() RETURNED (process exiting)");
        }
        else {
            BT("MainLoop: BEFORE g_MenuApplication->Show()");
            g_MenuApplication->Show();
            BT("MainLoop: Show() RETURNED (process exiting)");
        }
    }

}

// uMenu procedure: read sent storages, initialize RomFs (externally), load config and other stuff, finally create the renderer and start the UI

int main() {
    // v2.0.3-A1 first-paint telemetry: t_main captures the earliest user-code
    // entry point. Delta(t_main - t_appinit_ticks) approximates the cost of
    // libnx-time wiring + the static InitializeSettings cascade.
    g_qos_boot_t_main_ticks = armGetSystemTick();
    InitializeSettings();

    // W18-INPUT-STORAGE-RETRY: when uMenu is launched as the qlaunch override,
    // its parent (uSystem) is supposed to push two storages — LibAppletArgs
    // carrying the MenuStartMode, then a SystemStatus blob.  If uSystem is
    // slow to populate them (post-crash recovery boot, AM races, cold-start
    // ordering), appletPopInData returns 0x1159 (libnx::NotInitialized).
    // The previous unconditional UL_RC_ASSERT here turned that transient
    // race into a hard crash that bounced uMenu back to Atmosphère's fatal
    // screen.  Retry with a short backoff, then fall back to MainMenu +
    // zeroed SystemStatus so the user gets a usable desktop rather than a
    // bricked launcher.
    {
        Result rc_sm = 0;
        for(int i = 0; i < 16; ++i) {
            rc_sm = ul::menu::am::ReadStartMode(g_StartMode);
            if(R_SUCCEEDED(rc_sm)) {
                break;
            }
            UL_LOG_WARN("ReadStartMode attempt %d/%d rc=0x%08X — retrying in 100ms", i + 1, 16, rc_sm);
            svcSleepThread(100'000'000ULL);
        }
        if(R_FAILED(rc_sm) || g_StartMode == ul::smi::MenuStartMode::Invalid) {
            UL_LOG_WARN("ReadStartMode exhausted retries (rc=0x%08X, mode=%u) — defaulting to MainMenu", rc_sm, (u32)g_StartMode);
            g_StartMode = ul::smi::MenuStartMode::MainMenu;
        }
    }

    // Information sent as an extra storage to uMenu
    {
        Result rc_ss = 0;
        for(int i = 0; i < 16; ++i) {
            rc_ss = ul::menu::am::ReadFromInputStorage(&g_GlobalSettings.system_status, sizeof(g_GlobalSettings.system_status));
            if(R_SUCCEEDED(rc_ss)) {
                break;
            }
            UL_LOG_WARN("ReadFromInputStorage(system_status) attempt %d/%d rc=0x%08X — retrying in 100ms", i + 1, 16, rc_ss);
            svcSleepThread(100'000'000ULL);
        }
        if(R_FAILED(rc_ss)) {
            UL_LOG_WARN("ReadFromInputStorage(system_status) exhausted retries (rc=0x%08X) — defaulting to zeroed SystemStatus", rc_ss);
            g_GlobalSettings.system_status = {};
        }
    }
    g_GlobalSettings.initial_last_menu_index = g_GlobalSettings.system_status.last_menu_index;
    g_GlobalSettings.initial_last_menu_fs_path = g_GlobalSettings.system_status.last_menu_fs_path;
    UL_LOG_INFO("Start mode: %d, last path: '%s', last fs path: '%s', last menu index: %d", (u32)g_StartMode, g_GlobalSettings.system_status.last_menu_path, g_GlobalSettings.system_status.last_menu_fs_path, g_GlobalSettings.system_status.last_menu_index);

    // Check if our RomFs data exists...
    if(!ul::fs::ExistsFile(ul::MenuRomfsFile)) {
        UL_RC_ASSERT(ul::ResultRomfsNotFound);
    }

    // Try to mount it
    UL_RC_ASSERT(romfsMountFromFsdev(ul::MenuRomfsFile, 0, "romfs"));

    // Register handlers for HOME button press detection
    ul::menu::am::RegisterLibnxLibappletHomeButtonDetection();
    ul::menu::ui::QuickMenu::RegisterHomeButtonDetection();

    // v2.0.3-A1 first-paint telemetry: t_premain captures the moment before
    // MenuApplication::OnLoad runs (renderer init + theme + BGM + UI). Delta
    // (first-OnRender - t_premain) is the qd_DesktopIcons hot path on its own.
    g_qos_boot_t_premain_ticks = armGetSystemTick();
    MainLoop();

    return 0;
}
